# Generated by Django 3.2.15 on 2023-01-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_advocate_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cname',
            new_name='name',
        ),
    ]
